### ISSUE TITLE
error not sure what it is ?

### ISSUE THREAD

**Issue by Ibglitrbug** [unknowndev/CoolFish#45]
not sure what is happening it still works but keeps saying this over and over was hoping that with the update it would go away but it hasnt so bringing it to your attention. Im running addons but nothing else at the same time. 

[12:41:38.74 PM] [INFO] Casting Fishing
[12:41:52.30 PM] [ERROR] Unhandled error has occurred on another thread. This may cause an unstable state of the application.
[12:41:54.33 PM] [INFO] Caught a fish.
[12:41:55.45 PM] [INFO] Clicking bobber
[12:41:56.74 PM] [INFO] Casting Fishing
[12:42:10.93 PM] [INFO] Caught a fish.
[12:42:11.88 PM] [INFO] Clicking bobber
[12:42:13.65 PM] [INFO] Casting Fishing
[12:42:20.05 PM] [ERROR] Unhandled error has occurred on another thread. This may cause an unstable state of the application.
[12:42:29.09 PM] [ERROR] Unhandled error has occurred on another thread. This may cause an unstable state of the application.
[12:42:31.30 PM] [INFO] Caught a fish.
[12:42:31.94 PM] [INFO] Clicking bobber
[12:42:33.94 PM] [INFO] Casting Fishing

**Comment by unknowndev** [comment]
I'll see if I can find the root cause of this. Could you try to paste the log file (Logs directory) instead of the text in the CoolFish window?

**Comment by Ibglitrbug** [comment]
[01/04/15 12:39:51.3420 PM] [INFO] Logging at the [INFO] level and above only 
[01/04/15 12:39:51.8920 PM] [INFO] CoolFish Version: 4.1.0.3 
[01/04/15 12:39:51.9020 PM] [INFO] Loaded CoolFishBot-1.0.0.0 
[01/04/15 12:39:51.9220 PM] [INFO] Checking for a new version of CoolFish 
[01/04/15 12:39:52.2720 PM] [INFO] Attached to: 8076 
[01/04/15 12:39:52.3520 PM] [INFO] No new versions available. 
[01/04/15 12:40:34.4500 PM] [INFO] Starting bot... 
[01/04/15 12:40:34.5700 PM] [INFO] Started Engine 
[01/04/15 12:40:35.4840 PM] [INFO] Casting Fishing 
[01/04/15 12:40:52.9470 PM] [INFO] Caught a fish. 
[01/04/15 12:40:53.8400 PM] [INFO] Clicking bobber 
[01/04/15 12:40:55.7980 PM] [INFO] Casting Fishing 
[01/04/15 12:41:02.5920 PM] [INFO] Caught a fish. 
[01/04/15 12:41:04.1080 PM] [INFO] Clicking bobber 
[01/04/15 12:41:05.7150 PM] [INFO] Casting Fishing 
[01/04/15 12:41:15.5490 PM] [ERROR] Unhandled error has occurred on another thread. This may cause an unstable state of the application. 
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> Amazon.SQS.AmazonSQSException: Signature expired: 20150104T173953Z is now earlier than 20150104T182443Z (20150104T183943Z - 15 min.) ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.GenericHandler.<InvokeAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__1`1.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.GenericHandler.<InvokeAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

Hope this is what you want i could not put the whole log here it kept locking up the page.

**Comment by unknowndev** [comment]
Yes, this is exactly what I needed thanks.

The only time I've really seen this issue is when the system clock is much different from what the actual time should be. Do you use some kind of different time on your computer system from the actual time?

In either case, there is no real issue to be worried about from your end, but I'll see if I can find a fix to stop spamming the logs for you.

**Comment by Ibglitrbug** [comment]
yes my clock was set for the wrong time zone but was still canda and us just eastern instead of central.

**Comment by Ibglitrbug** [comment]
ill try it again now that i changed the clock see if it stops

**Comment by Ibglitrbug** [comment]
its running just fine now if it happens again i will let you know but so far it would have happened 3 times by now lol ty.

**Comment by unknowndev** [comment]
Thanks for your assistance with this issue.
