### ISSUE TITLE
[ERROR] Failed to attach do to an exception

### ISSUE THREAD

**Issue by incredibad** [unknowndev/CoolFish#46]
I keep getting the following error:

[4:40:23.25 PM] [ERROR] Failed to attach do to an exception.
[4:40:23.25 PM] [WARN] Failed to attach to: 5980

Coolfish Release 4.1.0.3

Running WIndows 8.1

I'm using 32 bit client and have the c++ redistributable installed (x86)

![32](https://cloud.githubusercontent.com/assets/2672295/5699738/a3d57688-9a7a-11e4-8861-c1864e0224ae.jpg)

![x86](https://cloud.githubusercontent.com/assets/2672295/5699742/ac1828b8-9a7a-11e4-9c45-22ddca6ec407.jpg)

Also running as administrator:

![adm](https://cloud.githubusercontent.com/assets/2672295/5699746/e7e62b7e-9a7a-11e4-9617-0fca90811a5a.jpg)

Error Log:

[01/12/15 4:40:23.0388 PM] [WARN] Logging at the [WARN] level and above only 
[01/12/15 4:40:23.2558 PM] [ERROR] Failed to attach do to an exception. 
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at CoolFishNS.Management.CoolManager.D3D.D3D11Device.LoadDxgiDll() in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\D3D\D3D11Device.cs:line 79
   at CoolFishNS.Management.CoolManager.D3D.D3D11Device.InitD3D(IntPtr& d3DDevicePtr) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\D3D\D3D11Device.cs:line 35
   at CoolFishNS.Management.CoolManager.D3D.D3DDevice..ctor(Process targetProcess, String d3DDllName) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\D3D\D3DDevice.cs:line 26
   at CoolFishNS.Management.CoolManager.D3D.Dirext3D..ctor(Process targetProc) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\D3D\Dirext3D.cs:line 13
   at CoolFishNS.Management.CoolManager.HookingLua.DxHook.Apply() in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\HookingLua\DxHook.cs:line 198
   at CoolFishNS.Management.BotManager.AttachToProcess(Process process) in c:\projects\coolfish\CoolFish\CoolFish\Management\BotManager.cs:line 158
[01/12/15 4:40:23.2558 PM] [WARN] Failed to attach to: 5980

**Comment by unknowndev** [comment]
Interesting issue. I have not come across this error before. I'll need more investigation to fix the issue. Have you tried running under DirectX9 mode instead of 11?

If that doesn't fix your issue you are more than welcome to try a beta build I have out here: https://ci.appveyor.com/api/buildjobs/4po9ee4v0qp28bha/artifacts/CoolFish/Build/x86/Debug/Debug_0.0.0.11.zip

It doesn't require any specific version of DirectX

**Comment by incredibad** [comment]
Hmm, neither of these options seem to work, keep getting the same error.

I tried the beta version with both dx9 and dx11, but same result.

It also keeps updating itself to 4.1.0.3 automatically, and I can't stop it. Gotta re-copy the files across each time lol.

**Comment by unknowndev** [comment]
Odd. I'll take a look and see if I can get back to you with some more options.

**Comment by incredibad** [comment]
Thanks mate, appreciate the quick response. Let me know if you need any more information from my end

**Comment by unknowndev** [comment]
I released a new version: https://github.com/unknowndev/CoolFish/releases/latest

Release 4.1.1.2 might fix your issue. See if you can try it back. If you have similar issues, could you post the log file text again so I can take a look? Thanks.

**Comment by incredibad** [comment]
Awesome seems to be working fine now, attaches properly without fuss.

Thanks for the update!
