### ISSUE TITLE
Error with new version

### ISSUE THREAD

**Issue by DublChen** [unknowndev/CoolFish#47]
[7:38:04.88 AM] [ERROR] Stopping bot because we could not execute code required to continue
[7:38:04.88 AM] [INFO] Engine Stopped

I get this after 30 or 40 seconds of the new version running.

**Comment by DublChen** [comment]
Let me give some additional information.  Version 4.1.1.2.  It only seems to happen if I minimize WoW (which is something I could do before).  Leave the WoW window open and it works fine.

**Comment by unknowndev** [comment]
thanks for the issue. I had not realized minimizing would cause this issue. Obviously, for a workaround while I fix it is to not minimize the window. I'll let you know when I have a chance to fix it. Background window still should work, just not minimize

**Comment by Sitromis** [comment]
Bought, downloaded, installed...

When I start WOW it claims to be in 64bit mode; duplicated the Wow.exe and renamed it to Wow-64.exe so when the client launches it, it still loads x86 - showing it on the login screen correctly.

Loaded Coolfish.exe and setup my setting; clicked "start" and received the "Please attach Wow process" error; tried to use the pull-down to select a process; no process are present; additionally the pull-down produces the " It seems you are running a 64bit version of WoW. CoolFish does not support that version. Please start the 32bit version instead." error consistently - even though I've forced it to load x86 version.

Any ideas?

**Comment by Northys** [comment]
@unknowndev :+1:

**Comment by drmDev** [comment]
I am having the exact same problem - it happens whether WoW is minimized or alt-tabbed (background). It works without a problem only if I keep the WoW window up in the foreground (preventing me from doing anything else on the computer). I hope you find a fix for this as it was very convenient to have this working in the background.

**Comment by unknowndev** [comment]
The bot should be able to run in background, but not minimized. To be fair minimized should have never worked, but now I know for sure it doesn't. Are you certain it does not work while in background but not minimized? If so, can you do some testing for me and send me some log files of you running it in forground and then switching it?

**Comment by drmDev** [comment]
Sure I would be glad to help out. Let me know how you want me to send the
log files. I'll run it again shortly - with window in foreground for a
minute then I will do alt and tab to put it in background. Usually within
the next cast the program stops and wow crashes complaining about not able
to execute code.

**Comment by drmDev** [comment]
What I see in the program itself:

[7:06:09.44 PM] [INFO] CoolFish Version: 4.1.1.2
[7:06:09.46 PM] [INFO] Loaded CoolFishBot-1.0.0.0
[7:06:09.48 PM] [INFO] Checking for a new version of CoolFish
[7:06:09.84 PM] [INFO] Attached to: 5576
[7:06:10.29 PM] [INFO] No new versions available.
[7:11:46.97 PM] [INFO] Attached to: 5576
[7:11:53.25 PM] [INFO] Starting bot...
[7:11:53.27 PM] [INFO] Started Engine
[7:11:55.52 PM] [INFO] Casting Fishing
[7:12:06.11 PM] [INFO] Caught a fish.
[7:12:06.64 PM] [INFO] Clicking bobber
[7:12:08.37 PM] [INFO] Casting Fishing
[7:12:22.77 PM] [INFO] Caught a fish.

.... Then I alt-tab and on the next cast:

[7:14:02.31 PM] [INFO] Casting Fishing
[7:14:14.97 PM] [ERROR] Stopping bot because we could not execute code required to continue
[7:14:15.16 PM] [INFO] Engine Stopped

=======================
Followed by WoW crashing with the following message:

Error #132 (0x85100084]) Fatal Exception

Program: C:\Program Files (x86)\World of Warcraft\Wow.exe
ProcessID: 5576
Exception: ACCESS_VIOLATION

The instruction at "0x002e0005" referenced memory at "0x01770010".
The memory could not be "read"

Press OK to terminate the application

===========================

And since you didn't request where to place the log, I'll just copy paste it here? The only difference I see in the log is the specific error within the code that produced it:

[02/20/15 7:14:14.9722 PM] [ERROR] Stopping bot because we could not execute code required to continue 
CoolFishNS.Exceptions.CodeInjectionFailedException: Failed to inject code after 10 seconds. Last Error: 3
   at CoolFishNS.Management.CoolManager.HookingLua.DxHook.InjectAndExecute(IEnumerable`1 asm) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\HookingLua\DxHook.cs:line 224
   at CoolFishNS.Management.CoolManager.HookingLua.DxHook.InternalExecute(IntPtr executeCommandPtr, IntPtr returnVarsNamesPtr, Int32 numberOfReturnVars, IntPtr returnVarsPtr) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\HookingLua\DxHook.cs:line 523
   at CoolFishNS.Management.CoolManager.HookingLua.DxHook.GetLocalizedText(IEnumerable`1 commands) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\HookingLua\DxHook.cs:line 0
   at CoolFishNS.Management.CoolManager.HookingLua.DxHook.GetLocalizedText(String command) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\HookingLua\DxHook.cs:line 378
   at CoolFishBotNS.FiniteStateMachine.States.StateDoWhisper.Run() in c:\projects\coolfish\CoolFish\CoolFishBot\FiniteStateMachine\States\StateDoWhisper.cs:line 48
   at CoolFishBotNS.FiniteStateMachine.CoolFishEngine.Pulse() in c:\projects\coolfish\CoolFish\CoolFishBot\FiniteStateMachine\CoolFishEngine.cs:line 159
   at CoolFishBotNS.FiniteStateMachine.CoolFishEngine.Run() in c:\projects\coolfish\CoolFish\CoolFishBot\FiniteStateMachine\CoolFishEngine.cs:line 175

================
Finally some more info that may or may not be relevant. I am running a 64 bit OS and have 64-bit WoW installed. However, when using this program I rename the 64-bit process and manually run the 32-bit WoW.exe process. I also play WoW in Fullscreen Mode as opposed to Windowed Mode. I don't know how else to put it simply in the background than Alt-tabbing, so that's all I do there. Let me know if there's anything else I can do to help you investigate this issue.

**Comment by unknowndev** [comment]
Ah, I see that might be the problem. I just tested running in full screen mode. When you alt-tab in full screen it does not simply put it in "background". It will in fact minimize the WoW window. This causes the problem you see. My suggestion would be to use Windowed mode and not use alt-tab. I'm working on a fix that should allow you to minimize, but it is not quite ready yet.
