### ISSUE TITLE
..Failed to Attach..

### ISSUE THREAD

**Issue by Sitromis** [unknowndev/CoolFish#48]
Greets.

I've got this purchased/installed and have configured the settings and am running the 32bit client.

NOTE: For those having issues with running the 32bit client of WOW, you HAVE TO use the launcher and set it correctly there before your game ID will appear in the 'attach' pull-down area.

Having gotten that far, I'm selecting my game ID and clicking the "attach" button; however, I continue to receive a "Failed to attach to: [id#]" error message.

Any idea's what might be causing this?

For further info; I've launched the game in both window, window (full screen) and full screen ... trying all three options.

**Comment by unknowndev** [comment]
First of all. I hope you didn't purchase this because it is provided completely free of charge. Second, if you could attach the full log file here, I can better help you diagnose your issue. Copy it from the "Logs" folder

**Comment by Sitromis** [comment]
Hmmm... well, I did but consider it a donation to the cause. Logs are below - 

[5:52:59 PM]  CoolFish Version: 2.1.0.6
[5:52:59 PM]  Loaded CoolFishBot-1.0.0.0
[5:52:59 PM]  Start Up.
[5:52:59 PM]  Base: 0x3D0000
[5:52:59 PM]  FrameScript_ExecuteBuffer: 0x2451D
[5:52:59 PM]  LastHardwareAction: 0xC32744
[5:52:59 PM]  s_curMgr: 0xCB9068
[5:52:59 PM]  LoadingScreen: 0xD936DE
[5:52:59 PM]  Timestamp: 0xC258A8
[5:52:59 PM]  CTM_Base: 0xD36508
[5:52:59 PM]  Failed to attach to: 11208
[5:53:00 PM]  System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at CoolFishNS.Utilities.Updater.<Update>b__0() in c:\Users\Unknown\SkyDrive\Projects\CoolFishGit\CoolFish\CoolFish\Utilities\Updater.cs:line 64
[5:53:04 PM]  Base: 0x3D0000
[5:53:04 PM]  FrameScript_ExecuteBuffer: 0x2451D
[5:53:04 PM]  LastHardwareAction: 0xC32744
[5:53:04 PM]  s_curMgr: 0xCB9068
[5:53:04 PM]  LoadingScreen: 0xD936DE
[5:53:04 PM]  Timestamp: 0xC258A8
[5:53:04 PM]  CTM_Base: 0xD36508
[5:53:04 PM]  Failed to attach to: 11208
[5:53:05 PM]  Base: 0x3D0000
[5:53:05 PM]  FrameScript_ExecuteBuffer: 0x2451D
[5:53:05 PM]  LastHardwareAction: 0xC32744
[5:53:05 PM]  s_curMgr: 0xCB9068
[5:53:05 PM]  LoadingScreen: 0xD936DE
[5:53:05 PM]  Timestamp: 0xC258A8
[5:53:05 PM]  CTM_Base: 0xD36508
[5:53:05 PM]  Failed to attach to: 11208
[5:53:53 PM]  CoolFishBot settings saved.
[5:53:55 PM]  Base: 0x3D0000
[5:53:55 PM]  FrameScript_ExecuteBuffer: 0x2451D
[5:53:55 PM]  LastHardwareAction: 0xC32744
[5:53:55 PM]  s_curMgr: 0xCB9068
[5:53:55 PM]  LoadingScreen: 0xD936DE
[5:53:55 PM]  Timestamp: 0xC258A8
[5:53:55 PM]  CTM_Base: 0xD36508
[5:53:55 PM]  Failed to attach to: 11208
[5:53:59 PM]  Base: 0x3D0000
[5:53:59 PM]  FrameScript_ExecuteBuffer: 0x2451D
[5:53:59 PM]  LastHardwareAction: 0xC32744
[5:53:59 PM]  s_curMgr: 0xCB9068
[5:53:59 PM]  LoadingScreen: 0xD936DE
[5:53:59 PM]  Timestamp: 0xC258A8
[5:53:59 PM]  CTM_Base: 0xD36508
[5:53:59 PM]  Failed to attach to: 11208
[5:56:59 PM]  Base: 0x3D0000
[5:56:59 PM]  FrameScript_ExecuteBuffer: 0x2451D
[5:56:59 PM]  LastHardwareAction: 0xC32744
[5:56:59 PM]  s_curMgr: 0xCB9068
[5:56:59 PM]  LoadingScreen: 0xD936DE
[5:56:59 PM]  Timestamp: 0xC258A8
[5:56:59 PM]  CTM_Base: 0xD36508
[5:56:59 PM]  Failed to attach to: 11208
[5:57:01 PM]  Base: 0x3D0000
[5:57:01 PM]  FrameScript_ExecuteBuffer: 0x2451D
[5:57:01 PM]  LastHardwareAction: 0xC32744
[5:57:01 PM]  s_curMgr: 0xCB9068
[5:57:01 PM]  LoadingScreen: 0xD936DE
[5:57:01 PM]  Timestamp: 0xC258A8
[5:57:01 PM]  CTM_Base: 0xD36508
[5:57:01 PM]  Failed to attach to: 11208
[5:57:01 PM]  Starting bot...
[5:57:01 PM]  Please attach to a WoW process.
[5:57:06 PM]  Base: 0x3D0000
[5:57:06 PM]  FrameScript_ExecuteBuffer: 0x2451D
[5:57:06 PM]  LastHardwareAction: 0xC32744
[5:57:06 PM]  s_curMgr: 0xCB9068
[5:57:06 PM]  LoadingScreen: 0xD936DE
[5:57:06 PM]  Timestamp: 0xC258A8
[5:57:06 PM]  CTM_Base: 0xD36508
[5:57:06 PM]  Failed to attach to: 11208
[5:58:23 PM]  CoolFishBot settings saved.
[5:58:43 PM]  Base: 0x3D0000
[5:58:43 PM]  FrameScript_ExecuteBuffer: 0x2451D
[5:58:43 PM]  LastHardwareAction: 0xC32744
[5:58:43 PM]  s_curMgr: 0xCB9068
[5:58:43 PM]  LoadingScreen: 0xD936DE
[5:58:43 PM]  Timestamp: 0xC258A8
[5:58:43 PM]  CTM_Base: 0xD36508
[5:58:43 PM]  Failed to attach to: 11208

**Comment by unknowndev** [comment]
You are using a very outdated version. Please download the latest version here: https://github.com/unknowndev/CoolFish/releases/latest

If you paid for this and didn't use the donate link in the bot, then you did not pay to the developer and paid for no reason.

**Comment by Sitromis** [comment]
Noted on both accounts. Thank you very much. It's good to onus of code!
