### ISSUE TITLE
wont attach it was working fine then i did the update and this started

### ISSUE THREAD

**Issue by Ibglitrbug** [unknowndev/CoolFish#51]
[03/03/15 2:21:09.4571 PM] [INFO] Logging at the [INFO] level and above only 
[03/03/15 2:21:10.7371 PM] [INFO] 
News: 
Coolfish for Wow 6.1.0 32-bit Client Only

Latest release should be working:
https://github.com/unknowndev/CoolFish/releases/latest

Follow me on twitter for updates:
https://twitter.com/TheUnknownDev

https://unknowndev.github.io/CoolFish/

 
[03/03/15 2:21:10.7371 PM] [INFO] CoolFish Version: 4.2.0.1 
[03/03/15 2:21:10.7771 PM] [INFO] Loaded CoolFishBot-2.0.0.0 
[03/03/15 2:21:10.7871 PM] [INFO] Checking for a new version of CoolFish 
[03/03/15 2:21:11.0771 PM] [ERROR] Failed to attach do to an exception. 
System.DllNotFoundException: Unable to load DLL 'FASM_1.71.21.DLL': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at CoolFishNS.Management.CoolManager.HookingLua.Asm.fasm_Assemble(IntPtr source, IntPtr mem, Int32 size, Int32 passes, IntPtr displayPipe)
   at CoolFishNS.Management.CoolManager.HookingLua.Asm.Assemble(String a, Int32 memSize, Int32 passLimit) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\HookingLua\Asm.cs:line 26
   at CoolFishNS.Management.CoolManager.HookingLua.DxHook.Inject(IEnumerable`1 asm, IntPtr address) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\HookingLua\DxHook.cs:line 56
   at CoolFishNS.Management.CoolManager.HookingLua.DxHook.Apply() in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\HookingLua\DxHook.cs:line 148
   at CoolFishNS.Management.BotManager.AttachToProcess(Process process) in c:\projects\coolfish\CoolFish\CoolFish\Management\BotManager.cs:line 167
[03/03/15 2:21:11.0771 PM] [WARN] Failed to attach to: 1184 
[03/03/15 2:21:11.3281 PM] [INFO] No new versions available. 
[03/03/15 2:21:17.0991 PM] [ERROR] Failed to attach do to an exception. 
System.DllNotFoundException: Unable to load DLL 'FASM_1.71.21.DLL': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at CoolFishNS.Management.CoolManager.HookingLua.Asm.fasm_Assemble(IntPtr source, IntPtr mem, Int32 size, Int32 passes, IntPtr displayPipe)
   at CoolFishNS.Management.CoolManager.HookingLua.Asm.Assemble(String a, Int32 memSize, Int32 passLimit) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\HookingLua\Asm.cs:line 26
   at CoolFishNS.Management.CoolManager.HookingLua.DxHook.Inject(IEnumerable`1 asm, IntPtr address) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\HookingLua\DxHook.cs:line 56
   at CoolFishNS.Management.CoolManager.HookingLua.DxHook.Apply() in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\HookingLua\DxHook.cs:line 148
   at CoolFishNS.Management.BotManager.AttachToProcess(Process process) in c:\projects\coolfish\CoolFish\CoolFish\Management\BotManager.cs:line 167
[03/03/15 2:21:17.0991 PM] [WARN] Failed to attach to: 1184

**Comment by Ibglitrbug** [comment]
hope this was the right log but i kept getting the failed to attach over and over restarted wow and tried redownloading this just nothing seem to work. 
thanks for your time

**Comment by unknowndev** [comment]
I'll take a look into fixing this for the next release

**Comment by unknowndev** [comment]
Merging as duplicate into this issue: https://github.com/unknowndev/CoolFish/issues/47
