### ISSUE TITLE
not attaching to wow so wont work is there a new version coming out?

### ISSUE THREAD

**Issue by Ibglitrbug** [unknowndev/CoolFish#54]
[4:31:44.28 PM] [INFO] CoolFish Version: 4.2.0.1
[4:31:44.42 PM] [INFO] Loaded CoolFishBot-2.0.0.0
[4:31:44.43 PM] [INFO] Checking for a new version of CoolFish
[4:31:44.89 PM] [ERROR] Failed to attach do to an exception.
[4:31:45.02 PM] [WARN] Failed to attach to: 18264
[4:31:45.03 PM] [INFO] No new versions available.

**Comment by unknowndev** [comment]
Can you paste the log file instead of the UI. It will be under the "Logs" folder in the CoolFish directory. There has been no changes, so it should still be working.

**Comment by bigmroot** [comment]
I'm having a similar issue.

[04/01/15 2:19:23.9708 PM] [ERROR] Exception thrown while finding offsets.  
System.IO.FileNotFoundException: Could not load file or assembly 'fasmdll_managed.dll' or one of its dependencies. The specified module could not be found.
File name: 'fasmdll_managed.dll'
   at GreyMagic.ExternalProcessReader..ctor(Process proc)
   at CoolFishNS.Management.CoolManager.FindPattern.ReadBytes(Process process, IntPtr address, Int32 count) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\FindPattern.cs:line 107
   at CoolFishNS.Management.CoolManager.FindPattern..ctor(Stream stream, Process process) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\FindPattern.cs:line 90
   at CoolFishNS.Management.CoolManager.Offsets.FindOffsets(Process proc) in c:\projects\coolfish\CoolFish\CoolFish\Management\CoolManager\Offsets.cs:line 43


[04/01/15 2:19:23.9708 PM] [WARN] Failed to attach to: 6736
