### ISSUE TITLE
 Unhandled error has occurred on another thread.

### ISSUE THREAD

**Issue by hnnweb** [unknowndev/CoolFish#57]
[4:25:57.10 PM] [ERROR] Unhandled error has occurred on another thread. This may cause an unstable state of the application.¨

ïs filling the window.

Pasting from Log:

[05/14/15 4:25:57.1060 PM] [ERROR] Unhandled error has occurred on another thread. This may cause an unstable state of the application. 
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> Amazon.SecurityToken.AmazonSecurityTokenServiceException: Not authorized to perform sts:AssumeRoleWithWebIdentity ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by unknowndev** [comment]
This is an expected behavior. I removed access to the mechanism that was sending data to AWS. I'm in the process of no longer supporting CoolFish. When the next patch comes out and CoolFish doesn't work, I will not longer be updating it.
